name: LLM_pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.8.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - audioread==3.0.1
      - bitarray==2.6.0
      - blobfile==3.0.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - coverage==7.6.12
      - datasets==2.18.0
      - decorator==5.2.1
      - dill==0.3.8
      - distro==1.9.0
      - editdistance==0.8.1
      - exceptiongroup==1.2.2
      - fairseq2==0.2.1
      - fairseq2n==0.2.1
      - filelock==3.17.0
      - fire==0.7.0
      - flake8==7.1.2
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.29.1
      - idna==3.10
      - importlib-metadata==7.2.1
      - importlib-resources==6.5.2
      - iniconfig==2.0.0
      - jinja2==3.1.5
      - jiter==0.8.2
      - jiwer==3.1.0
      - joblib==1.4.2
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llvmlite==0.44.0
      - lxml==5.3.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mccabe==0.7.0
      - mdurl==0.1.2
      - more-itertools==10.6.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - networkx==3.4.2
      - numba==0.61.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - openai-whisper==20240930
      - overrides==7.7.0
      - packaging==23.2
      - pandas==2.2.3
      - pathlib==1.0.1
      - pillow==11.1.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pooch==1.8.2
      - portalocker==3.1.1
      - propcache==0.3.0
      - psutil==5.9.8
      - pyarrow==19.0.1
      - pyarrow-hotfix==0.6
      - pycodestyle==2.12.1
      - pycparser==2.22
      - pycryptodomex==3.21.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pyflakes==3.2.0
      - pygments==2.19.1
      - pytest==8.3.5
      - pytest-cov==6.0.0
      - pytest-flake8==1.3.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - rapidfuzz==3.12.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - sacrebleu==2.5.1
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seamless-communication==1.0.0
      - sentence-transformers==3.4.1
      - sentencepiece==0.2.0
      - simuleval==1.1.4
      - six==1.17.0
      - sniffio==1.3.1
      - sonar-space==0.2.1
      - soundfile==0.13.1
      - sox==1.5.0
      - soxr==0.5.0.post1
      - sympy==1.13.1
      - tabulate==0.9.0
      - tbb==2022.0.0
      - tcmlib==1.2.0
      - termcolor==2.5.0
      - textgrid==1.6.1
      - threadpoolctl==3.5.0
      - tiktoken==0.9.0
      - tokenizers==0.21.0
      - tomli==2.2.1
      - torch==2.2.2
      - torchaudio==2.2.2
      - torcheval==0.0.7
      - tornado==6.4.2
      - tqdm==4.64.1
      - transformers==4.49.0
      - triton==2.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - xxhash==3.5.0
      - yarl==1.18.3
      - yt-dlp==2025.2.19
      - zipp==3.21.0
